# set leader
unbind C-b
set -g prefix C-Space
# bind C-Space send-prefix # set to send twice for nested tmux sessions

# set source for tmux binding
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# set mouse on for window resizing
set -g mouse on

# set vim motions for pane movement
set -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# visual config
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g status-position top
set -g status-justify centre

# behaviour config
set -sg escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# configure catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_date_time}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_connect_separator "no"
run "~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux"
